spring:
  application:
    name: gateway-app
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api-acceso-datos
          uri: lb://api-acceso-datos
          predicates:
            - Path=/api-acceso-datos/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: api-business
          uri: lb://api-business
          predicates:
            - Path=/api-business/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: api-public-users
          uri: lb://api-public-users
          predicates:
            - Path=/api-public-users/**
          filters:
            - RemoveRequestHeader=Cookie

server:
  servlet:
    context-path: /api-business
  port: 5004

