server:
  servlet:
    context-path: /api-acceso-datos
  port: 5005


spring:
  application:
    name: api-acceso-datos
  liquibase:
    change-log: classpath:/db/db.changelog.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true