server:
  servlet:
    context-path: /api-acceso-datos
  port: 5003


spring:
  application:
    name: api-acceso-datos
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tickets
    username: hashticket
    password: 12345678
  liquibase:
    change-log: classpath:/db/db.changelog.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: false
aws:
  accessKey: AKIAXLWLJTNPAYZ77O2O
  secretKey: 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

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace