spring:
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.30:5436/tickets
    username: hashticket
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: pool-tickets
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    show-sql: true
    generate-ddl: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

logging:
  config: classpath:log4j2-dev.xml
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace