eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:1111/eureka

business:
  pathRepo: /opt/repository/

endpoint:
  ms-data-access:
    protocol: http
    host: ${SERVER_DATOS}
    port: 5004
