spring:
  application:
    name: api-business
  profiles:
    active: dev
#  config:
#    import: optional:configserver:http://localhost:8888
server:
  servlet:
    context-path: /api-business
  port: 5003