eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

business:
  pathRepo: /Users/nicolas/Documents/repo_images/

endpoint:
  ms-data-access:
    protocol: http
    host: localhost
    port: 5003