eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:1111/eureka

business:
  pathRepo: /opt/repository/

endpoint:
  ms-data-access:
    protocol: http
    host: ${SERVER_DATOS}
    port: 5005

logging:
  config: classpath:log4j2-prod.xml

mail:
  configuration:
    user: admin@compraboletas.shop
    password: Nicole1310*

qr:
  path: /opt/repo_qr/