eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

business:
  pathRepo: /Users/nicolas/Documents/repo_images/

endpoint:
  ms-data-access:
    protocol: http
    host: localhost
    port: 5005

logging:
    config: classpath:log4j2-dev.xml

spring:
  sleuth:
    sampler:
      probability: 1.0
qr:
  path: /Users/nicolas/Documents/repo_qr/

mail:
  configuration:
    user: admin@compraboletas.shop
    password: Nicole1310*