spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/tickets
    url: jdbc:postgresql://5.183.8.146:5436/tickets
    username: hashticket
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: pool-tickets
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    show-sql: true
    generate-ddl: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

logging:
  config: classpath:log4j2-dev.xml
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace

mail:
  configuration:
    user: admin@compraboletas.shop
    password: Nicole1310*